### ISSUE TITLE
Perspective function should not be converted by mixin.

### ISSUE THREAD

**Issue by mnmly** [tj/nib#128]
There is `perspective` function available to the value of `transform` property: http://dev.w3.org/csswg/css3-3d-transforms/#transform-functions

But as there's perspective mixin is available in **nib**, it converts the `perspective(100px)` into `perspective: 100px`.

---
#### Input

``` css

section
  transform: perspective(500px)
```
#### Expected

``` css
section {
  -o-transform: perspective(500px);
  -webkit-transform: perspective(500px);
  -moz-transform: perspective(500px);
  transform: perspective(500px);
}
```
#### Result

``` css
section {
  -o-transform: perspective(: 500px);;;
  -webkit-transform: perspective(: 500px);;;
  -moz-transform: perspective(: 500px);;; 
  transform: perspective(: 500px);;;
}
```
