### ISSUE TITLE
null value

### ISSUE THREAD

**Issue by thejameskyle** [tj/nib#141]
Just an idea:

----
Stylus:
````sass
#foo
    margin 1em null
````
CSS:
````css
#foo {
    margin-top: 1em;
    margin-bottom: 1em;
}
`````

----

Stylus:
````sass
#foo
    margin null 1em
````
CSS:
````css
#foo {
    margin-left: 1em;
    margin-right: 1em;
}
`````

----

Stylus:
````sass
#foo
    margin 1em .5em null
````
CSS:
````css
#foo {
    margin-top: 1em;
    margin-right: .5em;    
    margin-right: .5em;
}
````

----
Stylus:

````sass
#foo
    margin null .5em 1em null
````
CSS:
````css
#foo {
    margin-right: .5em;    
    margin-bottom: 1em;
}
````
