### ISSUE TITLE
image() mixin doesn't work right inside @media queries

### ISSUE THREAD

**Issue by rstacruz** [tj/nib#157]
This is because Stylus doesn't support nested media queries yet, but trying to use `image()` inside a media query yields you unexpected results.

Practical use case: you want to use a smaller logo in smaller screens, and want them to be retina-compliant.

### Input

``` sass
@import nib
@media (max-width: 400px)
  .title
    display: block
  .logo
    image: 'logo.png'
```

### Expected output

``` css
@media (max-width: 400px) {
  .title {
    display: block;
  }
  .logo {
    background-image: url("logo.png");
  }
}
@media (max-width: 400px) and (-webkit-min-device-pixel-ratio: 1.5) {
  .logo {
    background-image: url("logo@2x.png");
    -webkit-background-size: auto auto;
    -moz-background-size: auto auto;
    background-size: auto auto;
  }
}
```

### Actual output

``` css
@media (max-width: 400px) {
  .title {
    display: block;
  }
  .logo {
    background-image: url("logo.png");
  }
@media all and (-webkit-min-device-pixel-ratio: 1.5) {
 {
      background-image: url("logo@2x.png");
      -webkit-background-size: auto auto;
      -moz-background-size: auto auto;
      background-size: auto auto;
    }
}
}
```
