### ISSUE TITLE
pathjoin() in image.styl converts folder structure to '\' instead of '/' in Windows

### ISSUE THREAD

**Issue by 2k0ri** [tj/nib#158]
input;

``` css
@import 'nib'
body
 image 'img/background.png'
```

excepted output:

``` css
body {
  background-image: url("img/background.png");
}
@media all and (-webkit-min-device-pixel-ratio: 1.5) {
  body {
    background-image: url("img/background@2x.png");
    -webkit-background-size: auto auto;
    -moz-background-size: auto auto;
    background-size: auto auto;
  }
}
```

actual output:

``` css
body {
  background-image: url("img/background.png");
}
@media all and (-webkit-min-device-pixel-ratio: 1.5) {
  body {
    background-image: url("img\background@2x.png");
    -webkit-background-size: auto auto;
    -moz-background-size: auto auto;
    background-size: auto auto;
  }
}
```

pathjoin() in `image.styl` converts folder structure to `\` instead of `/`.
