### ISSUE TITLE
rgba/hsla backward compatibility

### ISSUE THREAD

**Issue by alimd** [tj/nib#211]
I usually use hsla for my colors, and it not work in old browser.
I request to add backward compatibility like this

``` css
.selector{
  color: #hex;
  color: rgba(...);
}
```
