### ISSUE TITLE
Position shorthands not outputting correct top and left properties in CSS

### ISSUE THREAD

**Issue by arielserafini** [tj/nib#238]
Tested using nib@1.0.2

The following stylus code

``` stylus
a
  absolute 0 0
```

results in

``` css
a { 
  position:absolute;0:0;
}
```

when the expected result should be

``` css
a {
  position:absolute;
  left:0;
  top:0;
}
```
