### ISSUE TITLE
Incompatibility: media queries and hashes

### ISSUE THREAD

**Issue by gscottolson** [tj/nib#243]
My hashes won’t resolve when used with media queries. For example, the following fails to resolve:

``` stylus
$foo = {}
$foo.test = 'screen and (min-width:450px) and (max-width:600px)'
@media $foo.test
  p
    width: 100%
```

The resulting CSS:

``` css
@media $foo.test {
  p {
    width: 100%;
  }
}
```

A variable/media query combo will resolve though:

``` stylus
$baz = 'screen and (min-width:450px) and (max-width:600px)'
@media $baz
  p
    width: 100%
```

The resulting CSS:

``` css
@media screen and (min-width:450px) and (max-width:600px) {
  p {
    width: 100%;
  }
}
```

Is there a way to author this so the hash resolves?
