### ISSUE TITLE
linear-gradient acting weird

### ISSUE THREAD

**Issue by lan3jur** [tj/nib#295]
Hi.
I'm using Prepros to compile my stylus files, including nib and everything works fine except the linear gradient:
body
    background    linear-gradient(top, white, black)

outputs:
body {
  -webkit-background: linear-gradient(top, #fff, #000);
  -moz-background: linear-gradient(top, #fff, #000);
  -ms-background: linear-gradient(top, #fff, #000);
  -o-background: linear-gradient(top, #fff, #000);
  background: linear-gradient(top, #fff, #000);
}

Any suggestions? Thanks..

**Comment by slang800** [comment]
I get this as my output:

```css
body {
  background: -webkit-linear-gradient(top, #fff, #000);
  background: -moz-linear-gradient(top, #fff, #000);
  background: -o-linear-gradient(top, #fff, #000);
  background: -ms-linear-gradient(top, #fff, #000);
  background: linear-gradient(to bottom, #fff, #000);
}
```

...so this isn't a problem with nib. It's probably some issue in Prepros, but that's a piece of proprietary software so I can't fix that :(

You could try using [roots](http://roots.cx) or [gulp](http://gulpjs.com/) or [grunt](http://gruntjs.com/) to compile. Those are all free, open-source, and definitely work with nib.
