### ISSUE TITLE
Radial-gradient bug

### ISSUE THREAD

**Issue by L0une** [tj/nib#302]
Hello,
Here is a working code with linear-gradient:
```Stylus
testColor = #ff0000
.test
	background linear-gradient(testColor, #ffffff)
```
Here is a breaked code with radial-gradient:
```Stylus
testColor = #ff0000
.test
	background radial-gradient(testColor, #ffffff)
```
Any idea please?

**Comment by slang800** [comment]
works fine for me and compiles into:

```css
.test {
  background: -webkit-radial-gradient(#f00, #fff);
  background: -moz-radial-gradient(#f00, #fff);
  background: -o-radial-gradient(#f00, #fff);
  background: -ms-radial-gradient(#f00, #fff);
  background: radial-gradient(#f00, #fff);
}
```
