### ISSUE TITLE
size() doesn't work with !important

### ISSUE THREAD

**Issue by lazypacman** [tj/nib#314]
```css
div
  size 5px 10px !important 
```
produces
```css
div {
  width: 5px;
  height: 10px;
}
```
