### ISSUE TITLE
width: max-content doesn't come with webkit and moz prefix

### ISSUE THREAD

**Issue by transedward** [tj/nib#321]
if I use
```stylus
.foo
  width max-content
```

I only get
```css
.foo {
  width: max-content;
}
```

Not the output as below I expected
```css
.foo {
  width: -webkit-max-content;
  width: -moz-max-content;
  width: max-content;
}
```

Was that intentional?
