### ISSUE TITLE
nib and Stylus variables do not work well together

### ISSUE THREAD

**Issue by mitar** [tj/nib#333]
For this example:

```stylus
@import 'nib'

$input-transition ?= all .3s

.test
  transition $input-transition
  ```

The output without nib is:

```css
.test {
  -webkit-transition: all;
  -moz-transition: all;
  -o-transition: all;
  -ms-transition: all;
  transition: all;
}
```

But it should be more something like:

```css
.test {
  -webkit-transition: all 0.3s;
  -moz-transition: all 0.3s;
  -o-transition: all 0.3s;
  -ms-transition: all 0.3s;
  transition: all 0.3s;
}
```

If I do not use a variable, it works.

**Comment by skozin** [comment]
Hitting the same issue.

This:

```styl
.test
  $opacity-trans = opacity 0.2s linear
  transition $opacity-trans
```

incorrectly produces

```css
.test {
  transition: opacity;
}
```

However, this:

```styl
.test
  $opacity-trans = opacity 0.2s linear
  transition visibility 0s linear 0.2s, $opacity-trans
```

correctly produces

```css
.test {
  transition: visibility 0s linear 0.2s, opacity 0.2s linear;
}
```
