### ISSUE TITLE
-pos proposal

### ISSUE THREAD

**Issue by pgherveou** [tj/nib#53]
Hello TJ
what do you think about adding this line of code to the position helper, most of the time when I use fixed or absolute 
I fix the top/bottom and stretch the element setting both right and left. 

``` css

-pos(type, args)
  i = 0
  position: unquote(type)
  {args[i]}: args[i + 1] is a 'unit' ? args[i += 1] : 0
  {args[i += 1]}: args[i + 1] is a 'unit' ? args[i += 1] : 0
  if length(args) > i + 1
    {args[i += 1]}: args[i + 1] is a 'unit' ? args[i += 1] : 0

body
  fixed: top 0 right 5px left 5px


```
