### ISSUE TITLE
!important not preserved?

### ISSUE THREAD

**Issue by aseemk** [tj/nib#58]
A snippet like this:

``` stylus
selector
    opacity: 1 !important
```

Compiles to this for me:

``` css
selector{opacity:1;filter:progid:DXImageTransform.Microsoft.Alpha(Opacity=100)}
```

Note how `!important` wasn't preserved. Not sure if this is a Stylus bug or a Nib one, but I think Nib?

I'm running nib@0.3.2, which I think is the latest, but stylus@0.17.0, which is a bit old.
